name: Deploy to Cloud Run

on:
  workflow_dispatch:

env:
  SERVICE_NAME: nginx-hello
  REGION: us-central1
  PROJECT_ID: moonlit-haven-461710-g9
  IMAGE: us-central1-docker.pkg.dev/moonlit-haven-461710-g9/my-repo/nginx-hello
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud CLI
  uses: google-github-actions/setup-gcloud@v2
  with:
    project_id: ${{ env.PROJECT_ID }}
    service_account_key: ${{ secrets.GCP_SA_KEY }}
    export_default_credentials: true


      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev

      - name: Build and push container
        run: |
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated
